### PR TITLE
Cache the data for later redraws

### PR DESCRIPTION
**Pull request by rgbkrk**
Putting this up for @jdfreder to check out.

### CODE REVIEW

**Comment by jdfreder** [comment]
This is a good step, but like I mentioned in our chat, it would probably be best to have a custom model and to move the decoding into that.

**Comment by jdfreder** [comment]
Also, since you asked for it in the chat, I'll post some direction here.

To implement a custom model for this, the steps are very similar to the custom view.  

``` py
_model_module = Unicode('nbextensions/bitjet/bitjet', sync=True)
_model_name = Unicode('BitModel', sync=True)
```

In the JS, inside the define block,

```
   var BitModel = widget.WidgetModel.extend({
```

Remember, since you'll be writing code in the model, it won't be `this.model.get` or `this.model.on`, but instead `this.get` and `this.on`.  You may think it's silly for me to mention this, but it's easy to run into not so clear bugs if you make this mistake.

**Comment by rgbkrk** [comment]
That gets me started with framing, but I'm not sure what I'm overriding within the `extend`. I'll look at your flight widgets and ipython/ipython to see if I can figure it out.

**Comment by jdfreder** [comment]
@rgbkrk I don't use a custom model there.  The line I pasted should drop into your JS file inside the define block.  I think you just read too fast, in `var BitModel = widget.WidgetModel.extend({` the class you are extending is `WidgetModel` which != `DOMWidgetView`.

**Comment by jdfreder** [comment]
@rgbkrk if you want we can appear.in to talk about it.  I should be on Google talk for most of today.

**Comment by rgbkrk** [comment]
https://appear.in/jupyter

**Comment by rgbkrk** [comment]
My question is more along the lines of what I override. I made a shell of a BinaryModel here:

```
var BinaryModel = widget.WidgetModel.extend({
});
```

**Comment by rgbkrk** [comment]
Tempting to merge the views here too, but we'll let this standalone as the implementation of a model with a built in decoder.

**Pull request merged**
