### PR TITLE
Testing framework

### PR DESCRIPTION
**Pull request by rgbkrk**
:tophat: 

Introducing Travis, tox, and a minimal setup to the project.

### CODE REVIEW

**Comment by rgbkrk** [comment]
The JavaScript will be the worst part to test and is much of the "real" code here.

**Comment by rgbkrk** [comment]
```
    Installing nbextension ...

    error: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

Well that's no good, can't use `sudo=false` then I suppose...

**Comment by rgbkrk** [comment]
Blocker on this is https://github.com/jdfreder/jupyter-pip/issues/7. /cc @jdfreder

**Comment by jdfreder** [comment]
Thanks @rgbkrk looking into it right now...

**Comment by rgbkrk** [comment]
You're awesome!

**Comment by jdfreder** [comment]
@rgbkrk ipython-pip (AKA jupyter-pip) v.0.3 should address this.

**Comment by jdfreder** [comment]
Yay, looks like it passes!

**Pull request merged**
