### PR TITLE
s/ipythonpip/jupyterpip

### PR DESCRIPTION
**Pull request by jdfreder**
Hey @rgbkrk ,

Upon @minrk 's suggestion, I renamed my project to `jupyter-pip`.  I left the `ipython-pip` repo up on PYPI so nothing breaks, but if more bug fixes are made, they'll be made in the `jupyter-pip` PYPI repo.

### CODE REVIEW

**Comment by rgbkrk** [comment]
If you want tests to pass, you'll have to rebase against master. :wink:

**Comment by jdfreder** [comment]
Rebased

**Comment by rgbkrk** [comment]
:tada:

**Comment by rgbkrk** [comment]
I'm surprised you didn't name it `jupip`.

**Comment by jdfreder** [comment]
Too bad it's not still named `ipython-pip`, I could have named it `ippip`.

**Comment by rgbkrk** [comment]
`ipip`, do `upip`?

**Pull request merged**
